<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="market">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="payment" minOccurs="0" />
        <xs:element name="product" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:decimal" name="price"/>
              <xs:element type="xs:string" name="unit"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="account" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element name="transaction">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:decimal" name="balance"/>
                    <xs:element type="xs:string" name="datetime"/>
                    <xs:element type="xs:string" name="note" minOccurs="0"/>
                  </xs:sequence>
                  <xs:attribute type="xs:positiveInteger" name="id" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:positiveInteger" name="rows" default="2" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
